// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:1eceab64-b4e5-4a9e-827d-4616232f48c3",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_13mneOqxZ",
    "aws_user_pools_web_client_id": "15erdj132frinaj6rdl845nqc",
    "aws_appsync_graphqlEndpoint": "https://gti64m5emraovipthw6gjmhuae.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-m76axxwtobbopbnrvczbezg3tm",
    "aws_user_files_s3_bucket": "projectlaraveldc8fdda6d29842acad5a6dd32a7d42a3",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
